import {useEffect,useRef,useState,useId,type FormEvent} from "react";
import {Menu,X,Plus,Minus,Play,Pause,Check,Mail,Layers3,Globe2,Sparkles,Code2} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from "@/components/ui/select";
import {Checkbox} from "@/components/ui/checkbox";
import {forwardContactInquiry, type ContactInquiry} from "@/lib/contact-delivery";
import {assetPath} from "@/lib/assets";

const projects=[
 {id:"aether",name:"Aether",line:"A little clarity. A lot of possibility.",category:"Product design",tags:["Fintech","UX / UI"],description:"A calm, considered approach to personal finance. Everyday spending, savings, and future goals come together in one simple mobile experience.",challenge:"Make a complex financial picture feel understandable without overwhelming the person behind the numbers.",approach:"A goal-first structure, a focused home screen, and clear transaction patterns bring the most useful information forward.",scope:["Product strategy","User journeys","Mobile UI","Design system"]},
 {id:"forma",name:"Forma",line:"Care, in its most considered form.",category:"Brand identity",tags:["Beauty","Brand & commerce"],description:"An understated skincare identity with a warm, tactile digital experience. A complete brand world, from the shelf to the screen.",challenge:"Build a distinctive identity in a crowded category while making product choices feel simple and confident.",approach:"Sculptural packaging, a restrained visual system, and ingredient-led storytelling make the brand quietly distinctive.",scope:["Brand direction","Visual identity","Packaging concept","E-commerce UX"]},
 {id:"mono",name:"Mono",line:"Space for a different perspective.",category:"Web experience",tags:["Architecture","Website"],description:"A digital home for an architecture practice. An experience that lets spaces, materials, and light tell the story.",challenge:"Translate the scale and atmosphere of architecture into a website that works on every screen.",approach:"An editorial project index, immersive imagery, and deliberate motion keep the focus on the work, with a clear path to an inquiry.",scope:["Art direction","Website design","Responsive system","Motion direction"]},
 {id:"pulse",name:"Pulse",line:"A workspace that keeps things moving.",category:"Product design",tags:["SaaS","Product system"],description:"A collaborative planning concept that gives teams a shared picture of priorities, progress, and what happens next.",challenge:"Bring clarity to busy teams without introducing another complicated layer of work.",approach:"A consistent workspace, scannable tasks, and lightweight progress signals help people move from planning to action.",scope:["Information architecture","Dashboard UI","Interaction design","Component library"]},
 {id:"sora",name:"Sora",line:"Make room for a better headspace.",category:"Product design",tags:["Wellness","Mobile app"],description:"A gentle wellbeing app concept built around small daily rituals, thoughtful recommendations, and an unhurried experience.",challenge:"Encourage a useful daily habit without streak pressure, noise, or guilt.",approach:"Simple session choices, human language, and a warm visual system support a moment of calm.",scope:["Experience strategy","Mobile design","Content direction","Interactive prototype"]},
 {id:"oronix",name:"Oronix",line:"An identity with its own orbit.",category:"Brand identity",tags:["Studio identity","Digital brand"],description:"Our own starting point. An orbital symbol and expressive colour spectrum form an identity for a studio where creativity meets technology.",challenge:"Create an identity that moves comfortably between thoughtful product work and expressive digital experiences.",approach:"The original orbital mark remains at the centre. Electric blue, cyan, lilac, and pink connect the brand across typography, motion, and interaction.",scope:["Visual identity","Brand system","Interactive direction","Studio website"]}
];
type Project=typeof projects[number];
const services=[{title:"Product design",text:"Useful, intuitive digital products. From the first question to a system your team can build on.",tags:["UX research & strategy","Web & mobile UI","Design systems","Prototyping"],icon:Layers3},{title:"Brand identity",text:"A distinctive point of view, expressed consistently wherever people meet your brand.",tags:["Brand strategy","Visual identity","Art direction","Brand guidelines"],icon:Sparkles},{title:"Web experiences",text:"Beautiful websites with a purpose. Built to communicate clearly and turn curiosity into conversation.",tags:["Website design","Creative development","E-commerce","Responsive design"],icon:Globe2},{title:"Motion & interaction",text:"Details that make an experience feel alive, from purposeful transitions to playful 3D.",tags:["Motion direction","Micro-interactions","Interactive 3D","Creative prototyping"],icon:Code2}];

function Orbit(){
 const mount=useRef<HTMLDivElement>(null),control=useRef({paused:false,x:0,y:0});const[ready,setReady]=useState(false),[paused,setPaused]=useState(false);
 useEffect(()=>{let cancelled=false,cleanup=()=>{};const el=mount.current;if(!el)return;
 import("three").then(T=>{if(cancelled)return;let renderer:import("three").WebGLRenderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:"low-power"});}catch{return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0,0);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;el.appendChild(renderer.domElement);renderer.domElement.setAttribute("aria-hidden","true");
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,30);camera.position.z=8.2;
 const cv=document.createElement("canvas");cv.width=1024;cv.height=512;const ctx=cv.getContext("2d")!,g=ctx.createLinearGradient(0,0,1024,512);["#f5fbff","#00cbde","#0567fa","#c972ff","#ffbaba","#ffffff"].forEach((c,i)=>g.addColorStop(i/5,c));ctx.fillStyle=g;ctx.fillRect(0,0,1024,512);ctx.fillStyle="#fff";ctx.fillRect(100,80,90,340);ctx.fillRect(700,80,100,350);
 const tex=new T.CanvasTexture(cv);tex.mapping=T.EquirectangularReflectionMapping;const pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromEquirectangular(tex);scene.environment=env.texture;scene.add(new T.AmbientLight(0xffffff,2));const light=new T.DirectionalLight(0xffffff,4);light.position.set(3,5,4);scene.add(light);
 const group=new T.Group();scene.add(group);const mat=new T.MeshPhysicalMaterial({color:0xd4dcff,metalness:.94,roughness:.15,clearcoat:1,iridescence:.7,envMapIntensity:1.9}),geo=new T.TorusGeometry(1.43,.21,32,120),ogeo=new T.TorusGeometry(1.85,.105,24,120);group.add(new T.Mesh(geo,mat));const orbit=new T.Mesh(ogeo,mat);orbit.rotation.set(1.08,.3,-.6);group.add(orbit);group.rotation.set(.3,-.4,-.2);
 const sgeo=new T.SphereGeometry(.12,20,20),smat=new T.MeshPhysicalMaterial({color:0x0567fa,metalness:.8,roughness:.1}),satellite=new T.Mesh(sgeo,smat);scene.add(satellite);
 const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(el);resize();let visible=true,drag=false,lastX=0,lastY=0,px=0,py=0,rotation=0,frame=0;const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting});io.observe(el);const reduced=matchMedia("(prefers-reduced-motion:reduce)");
 const move=(e:PointerEvent)=>{const r=el.getBoundingClientRect();px=((e.clientX-r.left)/r.width-.5)*.35;py=((e.clientY-r.top)/r.height-.5)*.25;if(drag){control.current.y+=(e.clientX-lastX)*.008;control.current.x+=(e.clientY-lastY)*.008;lastX=e.clientX;lastY=e.clientY;}};
 const down=(e:PointerEvent)=>{drag=true;lastX=e.clientX;lastY=e.clientY;el.setPointerCapture(e.pointerId)},up=()=>{drag=false},lost=(e:Event)=>{e.preventDefault();setReady(false)},restored=()=>{resize();setReady(true)};
 el.addEventListener("pointermove",move);el.addEventListener("pointerdown",down);el.addEventListener("pointerup",up);el.addEventListener("pointercancel",up);renderer.domElement.addEventListener("webglcontextlost",lost);renderer.domElement.addEventListener("webglcontextrestored",restored);
 const tick=()=>{frame=requestAnimationFrame(tick);if(!visible||document.hidden)return;if(!control.current.paused&&!reduced.matches)rotation+=.002;group.rotation.x+=(.32+py+control.current.x-group.rotation.x)*.045;group.rotation.y+=(-.4+px+rotation+control.current.y-group.rotation.y)*.045;group.position.y=reduced.matches||control.current.paused?0:Math.sin(rotation*2)*.09;satellite.position.set(Math.cos(rotation+1)*2.25,Math.sin(rotation+1)*1.6,.5);renderer.render(scene,camera)};tick();setReady(true);
 cleanup=()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();el.removeEventListener("pointermove",move);el.removeEventListener("pointerdown",down);el.removeEventListener("pointerup",up);el.removeEventListener("pointercancel",up);renderer.domElement.removeEventListener("webglcontextlost",lost);renderer.domElement.removeEventListener("webglcontextrestored",restored);[geo,ogeo,sgeo,mat,smat,env,tex,pmrem,renderer].forEach(x=>x.dispose());renderer.domElement.remove()};
 }).catch(()=>{});return()=>{cancelled=true;cleanup()};},[]);
 return <div className="orbit-stage"><div ref={mount} className={"orbit-canvas "+(ready?"ready":"")} tabIndex={0} role="group" aria-label="Interactive Oronix orbit. Drag or use arrow keys to rotate." onKeyDown={e=>{if(e.key.startsWith("Arrow")){e.preventDefault();control.current.y+=e.key==="ArrowLeft"?-.2:e.key==="ArrowRight"?.2:0;control.current.x+=e.key==="ArrowUp"?-.2:e.key==="ArrowDown"?.2:0}}}><img className="orbit-fallback" src={assetPath("/brand/mark-dark.svg")} alt="Oronix orbit"/></div><div className="orbit-caption"><span>Ideas, in a new orbit.</span><button onClick={()=>{control.current.paused=!paused;setPaused(!paused)}} aria-label={paused?"Play animation":"Pause animation"}>{paused?<Play size={14}/>:<Pause size={14}/>}</button></div><span className="drag-label">DRAG TO EXPLORE</span></div>;
}
function Visual({p}:{p:Project}){
 if(["forma","mono"].includes(p.id))return <div className={"visual "+p.id}><img src={assetPath(`/projects/${p.id}.webp`)} alt={p.id==="forma"?"Forma skincare packaging in lavender and peach":"Sunlit sculptural architectural space"} loading="lazy"/><div className="visual-brand">{p.id==="forma"?"forma":"MONO"}<small>{p.id==="forma"?"Care in its purest form.":"Architecture, thoughtfully."}</small></div></div>;
 if(p.id==="oronix")return <div className="visual oronix"><img src={assetPath("/brand/mark.svg")} alt="Original Oronix orbit mark"/><img className="brand-word" src={assetPath("/brand/oronix-white.svg")} alt="Oronix"/><span>Research. Design. Development.</span></div>;
 if(p.id==="pulse")return <div className="visual pulse"><div className="visual-brand">pulse<small>Less noise. More flow.</small></div><div className="dashboard"><aside><b>✳ pulse</b>{["Overview","Projects","My tasks","Team"].map(x=><span className={x==="Projects"?"active":""} key={x}>{x}</span>)}<small>WORKSPACE</small><span>● Design team</span><span>● Engineering</span></aside><div className="dashboard-main"><div className="dash-top">Projects <span>Search anything &nbsp;⌘ K</span></div><h4>Good work starts here.</h4><p>Everything your team is moving forward.</p><div className="dash-stats">{["Active projects","Tasks completed","On track"].map((x,i)=><div key={x}><small>{x}</small><strong>{["12","84 / 120","92%"][i]}</strong></div>)}</div><div className="task-head">Project overview <span>This week</span></div>{["Website experience","Brand refresh","Mobile onboarding"].map((x,i)=><div className="task-row" key={x}><i>✳</i><b>{x}</b><div className="task-progress"><span style={{width:(65+i*10)+"%"}}/></div><span>{i===1?"In review":"In progress"}</span><em>{["JL","AK","MK"][i]}</em></div>)}</div></div></div>;
 if(p.id==="sora")return <div className="visual sora"><div className="visual-brand">sora<small>A softer kind of everyday.</small></div><div className="device sora-device"><div className="device-top">9:41 <span>● ▰</span></div><p className="app-greeting">A moment for yourself.</p><h4>How are you<br/>feeling today?</h4><div className="moods">{["Good","Okay","Low"].map((x,i)=><span key={x}>{["☺","◡","◠"][i]}<small>{x}</small></span>)}</div><div className="meditation"><small>YOUR DAILY PAUSE</small><h5>A little space<br/>to just be.</h5><p>◉ &nbsp; 8 min · Guided meditation</p></div><p className="session-title">Find your moment</p><div className="session">☼ &nbsp; A fresh start <span>5 min</span></div><div className="session">☾ &nbsp; Ease into evening <span>12 min</span></div></div><div className="sora-word">breathe.<br/>be here.</div></div>;
 return <div className="visual aether"><div className="visual-brand">aether<small>Money, with perspective.</small></div><div className="device device-back"><div className="device-top">9:41 <span>● ▰</span></div><small className="app-label">YOUR GOALS</small><h4>Think ahead.<br/>Start small.</h4><div className="goal"><span>◉</span><p>A place of your own</p><strong>₹2,40,000</strong><i/><small>48% of your goal</small></div><div className="goal"><p>A little adventure</p><strong>₹85,000</strong></div></div><div className="device device-front"><div className="device-top">9:41 <span>● ▰</span></div><p className="app-greeting">Good morning, Alex <span>◉</span></p><small className="app-label">TOTAL BALANCE</small><h4>₹1,24,850<span>.00</span></h4><p className="positive">+8.2% this month</p><svg className="finance-chart" viewBox="0 0 260 100" aria-hidden="true"><path d="M0 80 Q20 90 40 60 T80 68 T120 42 T165 55 T205 25 T260 10 V100 H0Z" fill="#2655fa" opacity=".09"/><path d="M0 80 Q20 90 40 60 T80 68 T120 42 T165 55 T205 25 T260 10" fill="none" stroke="#2655fa" strokeWidth="3"/></svg><div className="app-actions">{["Send","Add money","Save"].map((x,i)=><span key={x}>{["↗","＋","◉"][i]}<small>{x}</small></span>)}</div><div className="transaction"><span>A</span><p>Apple subscription<small>Today · Entertainment</small></p><b>− ₹199</b></div><div className="transaction"><span>↙</span><p>Monthly salary<small>Yesterday · Income</small></p><b>+ ₹85,000</b></div><div className="app-nav">⌂ &nbsp; ◴ &nbsp; ▦ &nbsp; ○</div></div></div>;
}
function Inquiry({close,inline=false}:{close?:()=>void;inline?:boolean}){
 const[service,setService]=useState(inline?"A bit of everything":""),[budget,setBudget]=useState(""),[consent,setConsent]=useState(false),[status,setStatus]=useState("idle"),[error,setError]=useState(""),[brief,setBrief]=useState("");
 const id=useRef(""),fingerprint=useRef(""),success=useRef<HTMLDivElement>(null);const prefix=useId(),serviceId=prefix+"-service",budgetId=prefix+"-budget",consentId=prefix+"-consent",errorId=prefix+"-error";
 useEffect(()=>{if(status==="success")success.current?.focus()},[status]);
 const reset=()=>{id.current="";fingerprint.current="";setService(inline?"A bit of everything":"");setBudget("");setConsent(false);setError("");setStatus("idle")};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{
  e.preventDefault();if(status==="saving")return;setError("");
  if(!service||!consent){setError("Choose a service and allow us to contact you about your project.");document.getElementById(!service?serviceId:consentId)?.focus();return}
  const data=new FormData(e.currentTarget),signature=JSON.stringify([Array.from(data.entries()),service,budget,consent]);
  if(fingerprint.current!==signature){id.current=crypto.randomUUID();fingerprint.current=signature}
  const text=(key:string)=>String(data.get(key)||"").trim();
  const p:ContactInquiry & {website:string;consent:true}={id:id.current,name:text("name"),email:text("email"),company:text("company"),message:text("message"),website:text("website"),service,budget,consent:true};
  if(p.website){setError("Please contact the studio by email.");return}
  if(!p.name||!p.email||p.message.length<10){setError("Enter your name, a valid email, and a message of at least 10 characters.");return}
  setStatus("saving");
  try{
   await forwardContactInquiry(p,new URL("./",window.location.href).href);
   setBrief(`Name: ${p.name}\nEmail: ${p.email}\nCompany: ${p.company}\nService: ${service}\nBudget: ${budget||"To be discussed"}\n\n${p.message}`);setStatus("success");
  }catch{setStatus("idle");setError("We couldn’t confirm your submission. Please try again or email oronixdesign@gmail.com directly.")}
 };
 if(status==="success")return <div ref={success} className="success" tabIndex={-1} role="status"><span><Check/></span>{inline?<h3>Thanks for reaching out.</h3>:<DialogTitle>Thanks for reaching out.</DialogTitle>}{inline?<p>Your inquiry has been submitted. We look forward to learning more about your project.</p>:<DialogDescription>Your inquiry has been submitted. We look forward to learning more about your project.</DialogDescription>}<a className="button primary" href={`mailto:oronixdesign@gmail.com?subject=${encodeURIComponent("A new project for Oronix")}&body=${encodeURIComponent(brief)}`}>Email a copy <Mail size={16}/></a><button className="text-button" onClick={inline?reset:close}>{inline?"Send another message":"Back to the studio"}</button></div>;
 return <><div className="form-intro">{!inline&&<span className="eyebrow">LET’S MAKE SOMETHING MATTER</span>}{inline?<h3>Contact us</h3>:<DialogTitle>Tell us what<br/>you have in mind.</DialogTitle>}{inline?<p>A project, a question, or just a hello. We’re listening.</p>:<DialogDescription>A new idea, a fresh start, or something that could work better. We’re listening.</DialogDescription>}</div><form className="inquiry-form" onSubmit={submit} aria-label={inline?"Contact Oronix":"Project inquiry"} aria-busy={status==="saving"} aria-describedby={error?errorId:undefined}><fieldset disabled={status==="saving"}><div className="field-row"><label>Your name<Input name="name" required maxLength={100} autoComplete="name" placeholder="Alex Morgan"/></label><label>Email address<Input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="alex@company.com"/></label></div><label>Company or brand <em>(optional)</em><Input name="company" maxLength={150} autoComplete="organization" placeholder="Your company"/></label>{!inline&&<div className="field-row"><label htmlFor={serviceId}>What can we help with?<Select value={service} onValueChange={setService}><SelectTrigger className="form-select" id={serviceId} aria-invalid={!!error&&!service}><SelectValue placeholder="Choose a service"/></SelectTrigger><SelectContent>{["Product design","Brand identity","Web experience","Motion & interaction","A bit of everything"].map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></label><label htmlFor={budgetId}>Project budget <em>(optional)</em><Select value={budget} onValueChange={setBudget}><SelectTrigger className="form-select" id={budgetId}><SelectValue placeholder="Let’s discuss"/></SelectTrigger><SelectContent>{["Under ₹1 lakh","₹1–3 lakh","₹3–5 lakh","₹5 lakh+","Let’s discuss"].map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></label></div>}<label>{inline?"Your message":"A little about your project"}<Textarea name="message" minLength={10} maxLength={4000} required rows={4} placeholder={inline?"Tell us about your project, question, or idea.":"What are you building, and what would you like to change?"}/></label><div className="honeypot" aria-hidden="true"><label>Website<Input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent"><Checkbox id={consentId} aria-invalid={!!error&&!consent} checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>You may contact me about this inquiry. My details will only be used to respond.</span></label>{error&&<p className="form-error" id={errorId} role="alert">{error}</p>}<button className="button primary" disabled={status==="saving"}>{status==="saving"?"Sending your inquiry…":inline?"Send message":"Send project inquiry"}</button><p className="direct-email">Prefer email? <a href="mailto:oronixdesign@gmail.com">oronixdesign@gmail.com</a></p></fieldset></form></>;
}
export default function Home(){
 const[menu,setMenu]=useState(false),[inquiry,setInquiry]=useState(false),[project,setProject]=useState<Project|null>(null),[filter,setFilter]=useState("All work"),[service,setService]=useState<number|null>(0),[faq,setFaq]=useState<number|null>(null);
 useEffect(()=>{const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("revealed");io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(e=>io.observe(e));return()=>io.disconnect()},[filter]);
 useEffect(()=>{
  type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown|Promise<unknown>};
  const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  const register=(tool:Tool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
  register({name:"list_design_concepts",title:"Explore Oronix concepts",description:"List the six concept projects with their disciplines and summaries. These are concept explorations, not verified client work.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>projects.map(({id,name,category,description})=>({id,name,category,description}))});
  register({name:"view_design_concept",title:"View a concept project",description:"Open the selected concept project in the same detail dialog used by the website.",inputSchema:{type:"object",properties:{id:{type:"string",enum:projects.map(p=>p.id)}},required:["id"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{const id=typeof input==="object"&&input!==null&&"id" in input?(input as {id:unknown}).id:null;const selected=projects.find(p=>p.id===id);if(!selected)throw new Error("Unknown concept project");setProject(selected);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {id:selected.id,view:"project details"}}});
  register({name:"start_project_inquiry",title:"Start a project inquiry",description:"Open the project inquiry form. This does not submit or save an inquiry.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async()=>{setProject(null);openInquiry();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {view:"project inquiry form",submitted:false}}});
  return()=>lifecycle.abort();
 },[]);
 const opener=useRef<HTMLElement|null>(null);
 const rememberOpener=()=>{const active=document.activeElement as HTMLElement|null;if(active&&!active.closest('[data-slot="dialog-content"]'))opener.current=active};
 const openInquiry=()=>{rememberOpener();setInquiry(true)};
 const openProject=(p:Project)=>{rememberOpener();setProject(p)};
 const restoreOpener=(event:Event)=>{event.preventDefault();if(opener.current?.isConnected)opener.current.focus()};
 const faqs=[{q:"What kind of projects do you take on?",a:"We work across digital product design, brand identity, websites, and motion. Whether you’re shaping an early idea or improving an established experience, we start by understanding what your project needs."},{q:"Can we work together remotely?",a:"Absolutely. Clear conversations, shared working files, and regular reviews keep the process collaborative wherever your team is based."},{q:"How do you scope a project?",a:"We begin with your goals, the work involved, and your timeline. Then we share a tailored scope with deliverables, milestones, and a clear project fee before getting started."},{q:"Can you help beyond the design?",a:"Yes. We can support creative website development, interactive prototypes, design systems, and the handoff to your engineering team. We’ll agree on the right level of support together."}];
 return <><a className="skip-link" href="#main">Skip to content</a><header className="header"><a href="#" aria-label="Oronix home"><img src={assetPath("/brand/oronix-dark.svg")} alt="Oronix"/></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#work">Work</a><a href="#services">Services</a><a href="#studio">Studio</a></nav><div className="header-right"><button className="button small primary" onClick={()=>openInquiry()}>Let’s talk <span>✳</span></button><button className="menu-toggle" aria-label={menu?"Close menu":"Open menu"} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="mobile-nav">{["Work","Services","Studio"].map(x=><a key={x} href={"#"+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<button onClick={()=>{setMenu(false);openInquiry()}}>Start a project</button></nav>}</header><main id="main">
 <section className="hero"><div className="hero-top"><span className="eyebrow">INDEPENDENT DESIGN STUDIO</span><span>A curious mind. A considered approach.</span></div><div className="hero-layout"><div className="hero-copy"><h1>Good design.<br/>Great <span>possibilities.</span></h1><p>We turn ambitious ideas into brands and digital experiences people love to use.</p><div className="hero-actions"><button className="button primary" onClick={()=>openInquiry()}>Start a project <span>✳</span></button><a href="#work" className="text-link">Explore our work <i/></a></div></div><Orbit/></div><div className="hero-bottom"><span>STRATEGY. DESIGN. A LITTLE WONDER.</span><a href="#work">Scroll to discover</a><span>CREATIVITY × TECHNOLOGY</span></div></section>
 <div className="marquee" aria-label="Our disciplines"><div className="marquee-track">{[0,1].map(i=><div key={i} aria-hidden={i===1}>{["Thoughtful strategy","Distinctive brands","Digital experiences","Human connections"].map(x=><span key={x}>{x}<i>✳</i></span>)}</div>)}</div></div>
 <section className="work section" id="work"><div className="section-heading reveal"><div><span className="eyebrow">01 / OUR DESIGN UNIVERSE</span><h2>Work with<br/><span>a point of view.</span></h2></div><div className="heading-aside"><p>Different challenges. A shared belief that good design should make a difference.</p><small>A collection of concept explorations.</small></div></div><div className="filters" role="group" aria-label="Filter projects">{["All work","Product design","Brand identity","Web experience"].map(x=><button key={x} className={filter===x?"selected":""} aria-pressed={filter===x} onClick={()=>setFilter(x)}>{x}{x==="All work"&&<span>06</span>}</button>)}</div><div className="project-grid">{projects.filter(p=>filter==="All work"||p.category===filter).map(p=><button key={p.id} className="project-card reveal" onClick={()=>openProject(p)} aria-label={`View ${p.name} concept project`}><Visual p={p}/><div className="project-info"><div><h3>{p.name}<span>/ 0{projects.indexOf(p)+1}</span></h3><p>{p.line}</p></div><span className="project-open"><Plus size={18}/></span></div><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}<small>Concept</small></div></button>)}</div></section>
 <section className="services section" id="services"><div className="section-heading reveal"><div><span className="eyebrow">02 / WHAT WE BRING</span><h2>From the big picture<br/><span>to the smallest detail.</span></h2></div><p className="heading-aside">One thoughtful partner for your brand, your product, and everything in between.</p></div><div className="services-layout"><div className="service-statement reveal"><img src={assetPath("/brand/mark.svg")} alt=""/><p>Good questions.<br/>Fresh perspectives.<br/><span>Better experiences.</span></p><button className="button light" onClick={()=>openInquiry()}>Find your starting point</button></div><div className="service-list">{services.map((s,i)=><div className="service-item" key={s.title}><button aria-expanded={service===i} aria-controls={"service-"+i} onClick={()=>setService(service===i?null:i)}><span>0{i+1}</span><s.icon size={24} strokeWidth={1.4}/><h3>{s.title}</h3>{service===i?<Minus size={18}/>:<Plus size={18}/>}</button><div className="service-content" id={"service-"+i} hidden={service!==i}><p>{s.text}</p><div>{s.tags.map(t=><span key={t}>{t}</span>)}</div></div></div>)}</div></div></section>
 <section className="studio section" id="studio"><div className="studio-top reveal"><span className="eyebrow">03 / THE WAY WE THINK</span><span className="sticker">Curiosity<br/>is our compass. ✳</span></div><div className="studio-copy reveal"><h2>Small by choice.<br/><span>Boundless by design.</span></h2><div><p>We’re Oronix. An independent design studio at the intersection of creativity and technology.</p><p>We believe the best work starts with listening. Understanding the people, asking the right questions, and making every decision count.</p><p>No layers of complexity. Just a thoughtful, collaborative process and a shared ambition to make something worth putting into the world.</p></div></div><div className="process-grid reveal">{[{title:"Discover",text:"We listen, question, and get close to the people and the problem."},{title:"Define",text:"We find the focus: the opportunity, the direction, and what success looks like."},{title:"Design",text:"We explore, prototype, and refine with you, turning a direction into an experience."},{title:"Deliver",text:"We bring it together with the systems and support to move confidently forward."}].map((p,i)=><article key={p.title}><span>0{i+1}<i>✳</i></span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></section>
 <section className="faq section"><div className="reveal"><span className="eyebrow">BEFORE WE SAY HELLO</span><h2>A few good<br/>questions.</h2></div><div className="faq-list reveal">{faqs.map((f,i)=><div className="faq-item" key={f.q}><button aria-expanded={faq===i} aria-controls={"faq-"+i} onClick={()=>setFaq(faq===i?null:i)}>{f.q}{faq===i?<Minus size={20}/>:<Plus size={20}/>}</button><p id={"faq-"+i} hidden={faq!==i}>{f.a}</p></div>)}</div></section>
 <section className="contact section" id="contact"><div className="contact-top"><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><span>Let’s make it a good one.</span></div><div className="contact-layout"><div className="contact-intro"><h2>Something<br/>on your mind<span>?</span></h2><p>Tell us about it. We’d love to help shape what’s next.</p><a className="contact-email" href="mailto:oronixdesign@gmail.com">oronixdesign@gmail.com</a><img className="contact-mark" src={assetPath("/brand/mark-dark.svg")} alt=""/></div><div className="contact-form-card"><Inquiry inline/></div></div></section>
 </main><footer className="footer"><div className="footer-top"><img src={assetPath("/brand/oronix-white.svg")} alt="Oronix"/><p>Thoughtful design.<br/>Extraordinary possibilities.</p><div><a href="#work">Work</a><a href="#services">Services</a><a href="#studio">Studio</a><button onClick={()=>openInquiry()}>Get in touch</button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Oronix Design Studio</span><span>Designed with intention. Built with curiosity.</span><a href="#">Back to top</a></div></footer>
 <Dialog open={inquiry} onOpenChange={setInquiry}><DialogContent className="inquiry-dialog" onCloseAutoFocus={restoreOpener}><Inquiry close={()=>setInquiry(false)}/></DialogContent></Dialog><Dialog open={!!project} onOpenChange={v=>{if(!v)setProject(null)}}><DialogContent className="project-dialog" onCloseAutoFocus={e=>{if(inquiry)e.preventDefault();else restoreOpener(e)}}>{project&&<><div className="detail-heading"><span className="eyebrow">CONCEPT EXPLORATION / {project.category.toUpperCase()}</span><DialogTitle>{project.name}</DialogTitle><DialogDescription>{project.line}</DialogDescription></div><Visual p={project}/><p className="detail-intro">{project.description}</p><div className="detail-columns"><div><h4>The challenge</h4><p>{project.challenge}</p></div><div><h4>The approach</h4><p>{project.approach}</p></div></div><div className="detail-scope"><h4>The design scope</h4><div>{project.scope.map(s=><span key={s}>{s}</span>)}</div></div><div className="detail-footer"><p>Have a similar challenge?</p><button className="button primary" onClick={()=>{setProject(null);openInquiry()}}>Let’s explore it</button></div></>}</DialogContent></Dialog></>;
}
